### ISSUE TITLE
Update to work with juniper master

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/juniper-from-schema#121]
It seems support for async GraphQL interfaces have landed in juniper master https://github.com/graphql-rust/juniper/pull/682.

I think the time has come to start updating juniper-from-schema to support the latest master of juniper with all the changes thats been made. We should also migrate all generated code to use the juniper proc macros rather than the old and deprecated declarative macros.

~~I suspect this is going to be quite a big task and require some work. I urge users to remain patient.~~ The work has begun!

# Todo

- [x] Docs section about specifically which versions of juniper are supported
- [x] Make sure changelog is up to date
- [x] Async resolver together with ownership: "as_ref"
- [x] Support subscriptions https://github.com/davidpdrsn/juniper-from-schema/pull/129
- [x] Support async https://github.com/davidpdrsn/juniper-from-schema/pull/128
- [x] Update changelog: Executor now requires two lifetimes but both can be elided 0bd023973977f
- [x] Re-export juniper and use that to pin its version https://github.com/davidpdrsn/juniper-from-schema/pull/125
- [x] Cannot declare scalar with same name as built-in https://github.com/davidpdrsn/juniper-from-schema/pull/124

**Comment by davidpdrsn** [comment]
https://github.com/davidpdrsn/juniper-from-schema/pull/122 is merged and we're now compatible with juniper master. At least all the tests are passing.

Still some work to be done around subscriptions and async. See the todo list in the top comment.

**Comment by davidpdrsn** [comment]
We now support async resolvers with a new `@juniper(async: true)` directive and the [`#[async_trait]`](https://docs.rs/async-trait/0.1.41/async_trait/) attribute. You can find an example [here](https://github.com/davidpdrsn/juniper-from-schema/blob/master/juniper-from-schema/examples/async.rs).

**Comment by davidpdrsn** [comment]
The master branch now supports juniper 0.15. I've made a milestone for the things remaining before doing a proper release https://github.com/davidpdrsn/juniper-from-schema/milestone/1.
